### ISSUE TITLE
[eleventy-plugin-styles] Cannot find module 'util/types'

### ISSUE THREAD

**Issue by lwojcik** [Halo-Lab/eleventy-packages#3]
I get the following error message while running `npx @11ty/eleventy`:

``Error` was thrown:
    Error: Cannot find module 'util/types'
    Require stack:
    - /Users/lukasz/workspace/offbeatbits/offbeatbits/node_modules/eleventy-plugin-styles/index.js
    - /Users/lukasz/workspace/offbeatbits/offbeatbits/.eleventy.js
    - /Users/lukasz/workspace/offbeatbits/offbeatbits/node_modules/@11ty/eleventy/src/TemplateConfig.js
    - /Users/lukasz/workspace/offbeatbits/offbeatbits/node_modules/@11ty/eleventy/src/Config.js
    - /Users/lukasz/workspace/offbeatbits/offbeatbits/node_modules/@11ty/eleventy/src/TemplateEngineManager.js
    - /Users/lukasz/workspace/offbeatbits/offbeatbits/node_modules/@11ty/eleventy/src/EleventyExtensionMap.js
    - /Users/lukasz/workspace/offbeatbits/offbeatbits/node_modules/@11ty/eleventy/src/TemplateRender.js
    - /Users/lukasz/workspace/offbeatbits/offbeatbits/node_modules/@11ty/eleventy/src/TemplateData.js
    - /Users/lukasz/workspace/offbeatbits/offbeatbits/node_modules/@11ty/eleventy/src/Eleventy.js
    - /Users/lukasz/workspace/offbeatbits/offbeatbits/node_modules/@11ty/eleventy/cmd.js
        at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
        at Function.Module._load (internal/modules/cjs/loader.js:746:27)
        at Module.require (internal/modules/cjs/loader.js:974:19)
        at require (internal/modules/cjs/helpers.js:93:18)
        at Object.<anonymous> (/Users/lukasz/workspace/offbeatbits/offbeatbits/node_modules/eleventy-plugin-styles/index.js:1:148)
        at Module._compile (internal/modules/cjs/loader.js:1085:14)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
        at Module.load (internal/modules/cjs/loader.js:950:32)
        at Function.Module._load (internal/modules/cjs/loader.js:790:12)
        at Module.require (internal/modules/cjs/loader.js:974:19)`

It happens in v1.4.0. Reverting to v1.3.3 fixes the problem.

Looks like it's related to Rollup config calling util/types as an external. I'll maybe try to have a look at it later next week.

**Comment by YevhenKap** [comment]
Hi! Thank you for the issue. It's strange. `util/types` is valid [module that is exposed from the API](https://nodejs.org/dist/latest-v16.x/docs/api/util.html#utiltypesisregexpvalue). What version of the Node do you use?

**Comment by lwojcik** [comment]
Oh shoot, I had v14 loaded in nvm. Switched to v16 and it now works fine. :)
